-- Advanced SQL Queries

-- 1. Employees with reporting structure
SELECT E.EMP_ID, E.FIRST_NAME, E.LAST_NAME, E.ROLE, E.DEPT,
COUNT(J.EMP_ID) AS EMP_REPORTING
FROM EMP_RECORD_TABLE E
JOIN EMP_RECORD_TABLE J
ON E.EMP_ID = J.MANAGER_ID
WHERE E.ROLE IN ('MANAGER','PRESIDENT','CEO')
GROUP BY E.EMP_ID;

-- 2. Department-wise max rating
SELECT E.EMP_ID, E.FIRST_NAME, E.LAST_NAME, E.ROLE, E.DEPT, E.EMP_RATING,
D.MAX_EMP_RATING
FROM EMP_RECORD_TABLE E
JOIN (
    SELECT DEPT, MAX(EMP_RATING) AS MAX_EMP_RATING
    FROM EMP_RECORD_TABLE
    GROUP BY DEPT
) D
ON E.DEPT = D.DEPT;

-- 3. Salary analysis by role
SELECT DEPT AS DEPARTMENT,
MIN(SALARY) AS MIN_SALARY,
MAX(SALARY) AS MAX_SALARY
FROM EMP_RECORD_TABLE
GROUP BY DEPT;

-- 4. Ranking by experience
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS EMPLOYEE_NAME,
EXP,
RANK() OVER (ORDER BY EXP ASC) AS EXPERIENCE_RANK
FROM EMP_RECORD_TABLE;

-- 5. Employees with experience > 10 years
SELECT EMP_ID, FIRST_NAME, LAST_NAME, DEPT, EXP
FROM EMP_RECORD_TABLE
WHERE EXP > 10;
