-- Basic Queries

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT 
FROM EMP_RECORD_TABLE 
ORDER BY DEPT;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING 
FROM EMP_RECORD_TABLE 
WHERE EMP_RATING < 2;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING 
FROM EMP_RECORD_TABLE 
WHERE EMP_RATING > 4;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING 
FROM EMP_RECORD_TABLE 
WHERE EMP_RATING BETWEEN 2 AND 4;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME, DEPT 
FROM EMP_RECORD_TABLE 
WHERE DEPT = 'FINANCE';

SELECT * 
FROM EMP_RECORD_TABLE 
WHERE DEPT IN ('HEALTHCARE','FINANCE');

SELECT EMP_ID,
CONCAT(FIRST_NAME,' ',LAST_NAME) AS EMPLOYEE_NAME,
ROLE, SALARY, EMP_RATING,
0.05*SALARY*EMP_RATING AS BONUS
FROM EMP_RECORD_TABLE;

SELECT COUNTRY, CONTINENT,
AVG(SALARY) OVER(PARTITION BY COUNTRY) AS AVG_COUNTRY_SAL,
AVG(SALARY) OVER(PARTITION BY CONTINENT) AS AVG_CONT_SAL
FROM EMP_RECORD_TABLE;
