-- ================================
-- DATABASE OBJECTS (ADVANCED SQL)
-- ================================

-- 1. VIEW: High salary employees
CREATE VIEW HIGH_SALARY_EMPLOYEES AS
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS EMPLOYEE_NAME,
COUNTRY, SALARY
FROM EMP_RECORD_TABLE
WHERE SALARY > 6000;

SELECT * FROM HIGH_SALARY_EMPLOYEES;

-- 2. STORED PROCEDURE: Employees with experience > 3 years
DELIMITER $$

CREATE PROCEDURE GET_EXPERIENCED_EMPLOYEES()
BEGIN
    SELECT * 
    FROM EMP_RECORD_TABLE 
    WHERE EXP > 3;
END $$

DELIMITER ;

CALL GET_EXPERIENCED_EMPLOYEES();

-- 3. FUNCTION: Job role classification
DELIMITER $$

CREATE FUNCTION JOB_PROFILE(EXP INT)
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
    DECLARE ROLE_DESC VARCHAR(100);

    IF EXP <= 2 THEN
        SET ROLE_DESC = 'JUNIOR DATA SCIENTIST';
    ELSEIF EXP <= 5 THEN
        SET ROLE_DESC = 'ASSOCIATE DATA SCIENTIST';
    ELSEIF EXP <= 10 THEN
        SET ROLE_DESC = 'SENIOR DATA SCIENTIST';
    ELSEIF EXP <= 12 THEN
        SET ROLE_DESC = 'LEAD DATA SCIENTIST';
    ELSE
        SET ROLE_DESC = 'MANAGER';
    END IF;

    RETURN ROLE_DESC;
END $$

DELIMITER ;

SELECT FIRST_NAME, LAST_NAME, EXP,
JOB_PROFILE(EXP) AS DESIGNATION
FROM EMP_RECORD_TABLE;

-- 4. INDEX: Improve search performance
CREATE INDEX IDX_FIRST_NAME
ON EMP_RECORD_TABLE(FIRST_NAME);

SELECT * 
FROM EMP_RECORD_TABLE
WHERE FIRST_NAME = 'Eric';
